language: node_js
bundler_args: --retry 0

node_js:
  - '6.10'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - npm run test:ci

after_success:
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info

env:
  global:
    - CXX=g++-4.8
    - secure: T+ziAC3vq5LZZM9WlCUVOUg3E9qJBhJR5QyuhIKKi5SRE7PZapLZe0kT32qts9MTNNLeC/4rirefYjnszA5bFpl5b65tr6C1FiPfHDLQj8leQM3o+N9Gu/ZiWtCF00ri1sK1fAPXBflTT+IuteFe9Wqr8jiDjPdmhgUbxV3UAINluH/Qvsj7CkE3W4kMQZZH/aIGIGsGxMUuFfXwPxccl4WrE43al2P+cbrsgh3rQS13rnmgephOQNu2RcrEBvnpXNy6xmJ70sBnSUlOyhl4YxX+4I86/Y+CT94LsuuCAoF52vhQ4dzRUHf1gwzzQeJbXhazqKuAYZImxWtyj/9GOs3p54FpiQliMHeZzIBFXwFCCvsscDRVddaFaLxIg6f5xTeA1QeL4QyNBemeCSLJgCesPvMIW2IRpxJO7FnncR5MgGSXnMFhqtVHwjYahzGOndZOcbThMBjJAiy7fF/lKD6NbfNkzRIvrmQsLdvjEPF6bfWaDYDqk/GbnYIvw4pcOwJ7AYYccZumBhVY2iyVHGHUTDdGZSgOSu6125QN5BhbEbfqNopo70HrCo8YQAl5Huz1eShzwXqeE11XLZhHsypSb3lJD0EZ7baMggI+OCYvkLzWHFVeSp2nNFx1ccsEniouf7QsMGdfaypqEIhsOdncRZJqbWZyc/Nn9YvDZFs=
